### PR TITLE
Update the root README with verbose configuration information

### PR DESCRIPTION
**Pull request by rickosborne**
To help out people who may not be super familiar with GPG configuration, and may have trouble debugging.

This is probably _far_ too verbose as-is, but it's an abbreviated version of the steps in #3 .

### CODE REVIEW

**Comment by Gby56** [comment]
I'm still struggling to understand why my touchID won't be prompted, and I have exactly the same setup as you're describing :/ My keychain has saved the gpg key's passphrase, I replaced my pinentry-program to /usr/local/bin/pinentry-touchid and it doesn't work... 
Git signing with pinentry-mac works though, but I only have to put my key passphrase once and it stays in memory (probably cache)
I tried adding `default-cache-ttl 1` `max-cache-ttl 1` but it's not working

**Comment by 0x3333** [comment]
My `pinentry-mac` doesn't have an option to Save to Keychain, so I cannot use pinentry-touchid. I tried everything I could. Tried GnuPG package, but nothing works.

**Comment by 0x3333** [comment]
Looks like the problem is a missing key in `defaults`:

```
defaults write org.gpgtools.pinentry-mac DisableKeychain -bool no
```

You must set this to NO, otherwise it will be "true" and doesn't show, even if you have `UseKeychain = yes`.

**Comment by inakiabt** [comment]
I can't get `pinentry-mac` to display the `Save in keychain` option, I've already tried:
- `defaults write org.gpgtools.pinentry-mac DisableKeychain -bool no`
- `defaults write org.gpgtools.pinentry-mac DisableKeychain -bool false`
- https://github.com/pstadler/keybase-gpg-github/issues/19#issuecomment-1189565494

**Review by jorgelbg — APPROVED** [review]

**Comment by jorgelbg** [comment]
@inakiabt Can you check if any of the suggestions in [this thread](https://gpgtools.tenderapp.com/discussions/problems/106038-pinentry-mac-not-displaying-save-to-keychain-checkbox) helps?

**Comment by inakiabt** [comment]
@jorgelbg 
```
killall gpg-agent
killall gpg2
killall gpg
killall dirmngr
```
Make it work. Thanks!

FYI:
```
$ defaults read org.gpgtools.common
{
    DisableKeychain = 0;
    UseKeychain = YES;
}
```

**Comment by jorgelbg** [comment]
Happy to hear that it is working!🎉 

pinentry-touchid should've been able to persist the password in the keychain even without the "Save in keychain" option in pinentry-mac. Curious why it didn't work 🤔. Would you mind sharing the logs from `$TMPDIR/pinentry-touchid.log`?

**Comment by inakiabt** [comment]
Since I wasn't seeing the "Save in keychain" option I didn't save my passphrase and then try `pinentry-touchid` 😅
I lost the logs at some point.

I'm automating this setup for my "dotfiles" setup, so I will try it in virtual machine I'm using and let you know.

**Pull request merged**
